"""create add method and category to endpoint

Revision ID: 003114751593
Revises: 2aa8d4039f2b
Create Date: 2024-04-08 09:36:22.859324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003114751593'
down_revision = '2aa8d4039f2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('method', sa.String(length=10), nullable=False))
    op.add_column('endpoint', sa.Column('category', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint', 'category')
    op.drop_column('endpoint', 'method')
    # ### end Alembic commands ###
