"""create endpoint_role table

Revision ID: 2aa8d4039f2b
Revises: 9ad9168c767e
Create Date: 2024-04-07 19:10:15.348705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa8d4039f2b'
down_revision = '9ad9168c767e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_role',
    sa.Column('endpoint_role_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.endpoint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_role_id')
    )
    op.create_index(op.f('ix_endpoint_role_endpoint_role_id'), 'endpoint_role', ['endpoint_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_role_endpoint_role_id'), table_name='endpoint_role')
    op.drop_table('endpoint_role')
    # ### end Alembic commands ###
