"""add UpdatePasswordLog table

Revision ID: 8971e936cb59
Revises: 003114751593
Create Date: 2024-11-16 10:32:40.881480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8971e936cb59'
down_revision = 'b4014796dcee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_password_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_update_password_log_log_id'), 'update_password_log', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_password_log_log_id'), table_name='update_password_log')
    op.drop_table('update_password_log')
    # ### end Alembic commands ###
