"""create endpoint table

Revision ID: 9ad9168c767e
Revises: b4014796dcee
Create Date: 2024-04-07 18:57:50.365420

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ad9168c767e"
down_revision = "b4014796dcee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoint",
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("endpoint_name", sa.String(length=256), nullable=False),
        sa.Column("is_common", sa.Boolean(), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("endpoint_id"),
        sa.UniqueConstraint("endpoint_name"),
    )
    op.create_index(
        op.f("ix_endpoint_endpoint_id"), "endpoint", ["endpoint_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_endpoint_endpoint_id"), table_name="endpoint")
    op.drop_table("endpoint")
    # ### end Alembic commands ###
